<?php
header('Content-type: application/json');
require_once '../initialization.php';
use Hourglass\Managers\Caller;
use Hourglass\Managers\VersionningManager;

/**
*	===================================================================================
* 	BEGIN: Enter below the requests you want to be cached into $REQUESTS_TO_BE_CACHED
*	===================================================================================
*/

// [Example 1] the classic 'checkout'...
array_push($REQUESTS_TO_BE_CACHED, '{"method":"checkout"}');

// [Example 2] Generate all the requests pull from each revision to latest one
$latestVersionRevisionNumber = (new VersionningManager(HISTORY_FILE_PATH, FOLDER_TO_BE_VERSIONNED_FILE_PATH))->getRevNumber();
for($revision = 1; $revision <= $latestVersionRevisionNumber; $revision++) {
	array_push($REQUESTS_TO_BE_CACHED, '{"method":"pullFromRevision","params":{"revision":'.$revision.'}}');
}

// [Example 3] Why not about request including filters...
// array_push($REQUESTS_TO_BE_CACHED, '{"method":"checkout","params":{"filterWithRegex":".*.jpg|.*.jpeg|.*.JPG"}');
// array_push($REQUESTS_TO_BE_CACHED, '{"method":"checkout","params":{"filterWithoutRegex":".*.png"}');

// [Example N... do yours...]
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...

/**
*	===================================================================================
* 	END cachec request declaration
*	===================================================================================
*/

function writeScreenAndLog($logMessage) {
	print $logMessage."\r\n\r\n";
	Logger::getRootLogger()->debug($logMessage);
}

// Don't touch this now anymore... We are executing the requests...
foreach ($REQUESTS_TO_BE_CACHED as $request) {
	$requestFingerprint = md5($request);
	writeScreenAndLog("START Generating cache for request <".$requestFingerprint."> aka ". $request);
	$jsonResponse = Caller::handle((isset($request) ? $request : null), 'System', 'CacheGenerator');
	writeScreenAndLog("END of cache generation for request <".$requestFingerprint.">, result is: ". $jsonResponse);
}


